### ISSUE TITLE
Grade: Meets Expectations

### ISSUE THREAD

**Issue by Rodrigap** [SiliconSurfer13/Tea-Cozy#4]
Nice job on this! Your HTML and CSS are both fully functional, your finished product looks just like the spec. I didn't have any major critiques, just a minor critique about some inconsistent HTML indentation. I can see that you get the idea of it, but some spots don't match up with each other. I'd also suggest adding comments to your CSS! It increases your CSS organization if you group things by section, almost like you do in your HTML, and add comments to label each one. Lastly, remember that you're free to elaborate on the spec and add extra HTML sections or extra styling! You can get creative with it and all extra colors/fonts/etc. Overall, great job!

**Comment by SiliconSurfer13** [comment]
Thanks for the feedback. Will definitely work on the indentation. I got lazy with commenting my CSS :-)
